#include "bytecode.h"
#include <stdio.h>

#define STACK_SIZE 4096
#define PROGRAM_SIZE 4096
#define DATA_SIZE 4096
unsigned int jvm_program[STACK_SIZE]; // ok, global
unsigned int jvm_stack[STACK_SIZE]; // ok, global
unsigned int jvm_data[DATA_SIZE]; // ok, global
//BYTECODE_LUT byte_code_lut[256]= {0};

BYTECODE_LUT byte_code_lut[256]={ {0} };
VMPROC vmproc;
VMPROC *vp=&vmproc;


unsigned int print_bytecode(unsigned int *java_program, unsigned int pc)
{
   unsigned char op=java_program[pc];
   printf("%04x %s (%d)", pc, byte_code_lut[op].mnem, byte_code_lut[op].n );
   return pc;
}
unsigned int execute_bytecode(unsigned int *java_program, unsigned int pc) {
    PRM prm;
   unsigned char op=java_program[pc];
   int result = byte_code_lut[op].vf(&prm);
   pc++;
   return pc;
}

// autogenerated from wikipedia by bytecode.pl
// https://en.wikipedia.org/wiki/Java_bytecode_instruction_listings


int vf_aaload(PRM *p)
{
	printf("aaload");
}
int vf_aastore(PRM *p)
{
	printf("aastore");
}
int vf_aconst_null(PRM *p)
{
	printf("aconst_null");
}
int vf_aload(PRM *p)
{
	printf("aload");
}
int vf_aload_0(PRM *p)
{
	printf("aload_0");
}
int vf_aload_1(PRM *p)
{
	printf("aload_1");
}
int vf_aload_2(PRM *p)
{
	printf("aload_2");
}
int vf_aload_3(PRM *p)
{
	printf("aload_3");
}
int vf_anewarray(PRM *p)
{
	printf("anewarray");
}
int vf_areturn(PRM *p)
{
	printf("areturn");
}
int vf_arraylength(PRM *p)
{
	printf("arraylength");
}
int vf_astore(PRM *p)
{
	printf("astore");
}
int vf_astore_0(PRM *p)
{
	printf("astore_0");
}
int vf_astore_1(PRM *p)
{
	printf("astore_1");
}
int vf_astore_2(PRM *p)
{
	printf("astore_2");
}
int vf_astore_3(PRM *p)
{
	printf("astore_3");
}
int vf_athrow(PRM *p)
{
	printf("athrow");
}
int vf_baload(PRM *p)
{
	printf("baload");
}
int vf_bastore(PRM *p)
{
	printf("bastore");
}
int vf_bipush(PRM *p)
{
	printf("bipush");
}
int vf_breakpoint(PRM *p)
{
	printf("breakpoint");
}
int vf_caload(PRM *p)
{
	printf("caload");
}
int vf_castore(PRM *p)
{
	printf("castore");
}
int vf_checkcast(PRM *p)
{
	printf("checkcast");
}
int vf_d2f(PRM *p)
{
	printf("d2f");
}
int vf_d2i(PRM *p)
{
	printf("d2i");
}
int vf_d2l(PRM *p)
{
	printf("d2l");
}
int vf_dadd(PRM *p)
{
	printf("dadd");
}
int vf_daload(PRM *p)
{
	printf("daload");
}
int vf_dastore(PRM *p)
{
	printf("dastore");
}
int vf_dcmpg(PRM *p)
{
	printf("dcmpg");
}
int vf_dcmpl(PRM *p)
{
	printf("dcmpl");
}
int vf_dconst_0(PRM *p)
{
	printf("dconst_0");
}
int vf_dconst_1(PRM *p)
{
	printf("dconst_1");
}
int vf_ddiv(PRM *p)
{
	printf("ddiv");
}
int vf_dload(PRM *p)
{
	printf("dload");
}
int vf_dload_0(PRM *p)
{
	printf("dload_0");
}
int vf_dload_1(PRM *p)
{
	printf("dload_1");
}
int vf_dload_2(PRM *p)
{
	printf("dload_2");
}
int vf_dload_3(PRM *p)
{
	printf("dload_3");
}
int vf_dmul(PRM *p)
{
    p->d[1] = p->d[1] * p->d[2];
    //push result
    // pc++
	printf("dmul");
}
int vf_dneg(PRM *p)
{
	printf("dneg");
}
int vf_drem(PRM *p)
{
	printf("drem");
}
int vf_dreturn(PRM *p)
{
	printf("dreturn");
}
int vf_dstore(PRM *p)
{
	printf("dstore");
}
int vf_dstore_0(PRM *p)
{
	printf("dstore_0");
}
int vf_dstore_1(PRM *p)
{
	printf("dstore_1");
}
int vf_dstore_2(PRM *p)
{
	printf("dstore_2");
}
int vf_dstore_3(PRM *p)
{
	printf("dstore_3");
}
int vf_dsub(PRM *p)
{
	printf("dsub");
}
int vf_dup(PRM *p)
{
	printf("dup");
}
int vf_dup_x1(PRM *p)
{
	printf("dup_x1");
}
int vf_dup_x2(PRM *p)
{
	printf("dup_x2");
}
int vf_dup2(PRM *p)
{
	printf("dup2");
}
int vf_dup2_x1(PRM *p)
{
	printf("dup2_x1");
}
int vf_dup2_x2(PRM *p)
{
	printf("dup2_x2");
}
int vf_f2d(PRM *p)
{
	printf("f2d");
}
int vf_f2i(PRM *p)
{
	printf("f2i");
}
int vf_f2l(PRM *p)
{
	printf("f2l");
}
int vf_fadd(PRM *p)
{
	printf("fadd");
}
int vf_faload(PRM *p)
{
	printf("faload");
}
int vf_fastore(PRM *p)
{
	printf("fastore");
}
int vf_fcmpg(PRM *p)
{
	printf("fcmpg");
}
int vf_fcmpl(PRM *p)
{
	printf("fcmpl");
}
int vf_fconst_0(PRM *p)
{
	printf("fconst_0");
}
int vf_fconst_1(PRM *p)
{
	printf("fconst_1");
}
int vf_fconst_2(PRM *p)
{
	printf("fconst_2");
}
int vf_fdiv(PRM *p)
{
	printf("fdiv");
}
int vf_fload(PRM *p)
{
	printf("fload");
}
int vf_fload_0(PRM *p)
{
	printf("fload_0");
}
int vf_fload_1(PRM *p)
{
	printf("fload_1");
}
int vf_fload_2(PRM *p)
{
	printf("fload_2");
}
int vf_fload_3(PRM *p)
{
	printf("fload_3");
}
int vf_fmul(PRM *p)
{
	printf("fmul");
}
int vf_fneg(PRM *p)
{
	printf("fneg");
}
int vf_frem(PRM *p)
{
	printf("frem");
}
int vf_freturn(PRM *p)
{
	printf("freturn");
}
int vf_fstore(PRM *p)
{
	printf("fstore");
}
int vf_fstore_0(PRM *p)
{
	printf("fstore_0");
}
int vf_fstore_1(PRM *p)
{
	printf("fstore_1");
}
int vf_fstore_2(PRM *p)
{
	printf("fstore_2");
}
int vf_fstore_3(PRM *p)
{
	printf("fstore_3");
}
int vf_fsub(PRM *p)
{
	printf("fsub");
}
int vf_getfield(PRM *p)
{
	printf("getfield");
}
int vf_getstatic(PRM *p)
{
	printf("getstatic");
}
int vf_goto(PRM *p)
{
	printf("goto");
}
int vf_goto_w(PRM *p)
{
	printf("goto_w");
}
int vf_i2b(PRM *p)
{
	printf("i2b");
}
int vf_i2c(PRM *p)
{
	printf("i2c");
}
int vf_i2d(PRM *p)
{
	printf("i2d");
}
int vf_i2f(PRM *p)
{
	printf("i2f");
}
int vf_i2l(PRM *p)
{
	printf("i2l");
}
int vf_i2s(PRM *p)
{
	printf("i2s");
}
// iadd 60 0110 0000  value1, value2 → result add two ints
int vf_iadd(PRM *p)
{
	printf("iadd %d %d",p->i[1],p->i[2]);
	p->i[0] = p->i[1] + p->i[2];
	vp->pc++;
	return( p->i[0] );
}
int vf_iaload(PRM *p)
{
	printf("iaload");
}
int vf_iand(PRM *p)
{
	printf("iand");
}
int vf_iastore(PRM *p)
{
	printf("iastore");
}
int vf_iconst_m1(PRM *p)
{
	printf("iconst_m1");
}
int vf_iconst_0(PRM *p)
{
	printf("iconst_0");
}
int vf_iconst_1(PRM *p)
{
	printf("iconst_1");
}
int vf_iconst_2(PRM *p)
{
	printf("iconst_2");
}
int vf_iconst_3(PRM *p)
{
	printf("iconst_3");
}
int vf_iconst_4(PRM *p)
{
	printf("iconst_4");
}
int vf_iconst_5(PRM *p)
{
	printf("iconst_5");
}
int vf_idiv(PRM *p)
{
	printf("idiv");
}
int vf_if_acmpeq(PRM *p)
{
	printf("if_acmpeq");
}
int vf_if_acmpne(PRM *p)
{
	printf("if_acmpne");
}
int vf_if_icmpeq(PRM *p)
{
	printf("if_icmpeq");
}
int vf_if_icmpge(PRM *p)
{
	printf("if_icmpge");
}
int vf_if_icmpgt(PRM *p)
{
	printf("if_icmpgt");
}
int vf_if_icmple(PRM *p)
{
	printf("if_icmple");
}
int vf_if_icmplt(PRM *p)
{
	printf("if_icmplt");
}
int vf_if_icmpne(PRM *p)
{
	printf("if_icmpne");
}
int vf_ifeq(PRM *p)
{
	printf("ifeq");
}
int vf_ifge(PRM *p)
{
	printf("ifge");
}
int vf_ifgt(PRM *p)
{
	printf("ifgt");
}
int vf_ifle(PRM *p)
{
	printf("ifle");
}
int vf_iflt(PRM *p)
{
	printf("iflt");
}
int vf_ifne(PRM *p)
{
	printf("ifne");
}
int vf_ifnonnull(PRM *p)
{
	printf("ifnonnull");
}
int vf_ifnull(PRM *p)
{
	printf("ifnull");
}
int vf_iinc(PRM *p)
{
	printf("iinc");
}
int vf_iload(PRM *p)
{
	printf("iload");
}
int vf_iload_0(PRM *p)
{
	printf("iload_0");
}
int vf_iload_1(PRM *p)
{
	printf("iload_1");
}
int vf_iload_2(PRM *p)
{
	printf("iload_2");
}
int vf_iload_3(PRM *p)
{
	printf("iload_3");
}
int vf_impdep1(PRM *p)
{
	printf("impdep1");
}
int vf_impdep2(PRM *p)
{
	printf("impdep2");
}
int vf_imul(PRM *p)
{
	printf("imul");
}
int vf_ineg(PRM *p)
{
	printf("ineg");
}
int vf_instanceof(PRM *p)
{
	printf("instanceof");
}
int vf_invokedynamic(PRM *p)
{
	printf("invokedynamic");
}
int vf_invokeinterface(PRM *p)
{
	printf("invokeinterface");
}
int vf_invokespecial(PRM *p)
{
	printf("invokespecial");
}
int vf_invokestatic(PRM *p)
{
	printf("invokestatic");
}
int vf_invokevirtual(PRM *p)
{
	printf("invokevirtual");
}
int vf_ior(PRM *p)
{
	printf("ior");
}
int vf_irem(PRM *p)
{
	printf("irem");
}
int vf_ireturn(PRM *p)
{
	printf("ireturn");
}
int vf_ishl(PRM *p)
{
	printf("ishl");
}
int vf_ishr(PRM *p)
{
	printf("ishr");
}
int vf_istore(PRM *p)
{
	printf("istore");
}
int vf_istore_0(PRM *p)
{
	printf("istore_0");
}
int vf_istore_1(PRM *p)
{
	printf("istore_1");
}
int vf_istore_2(PRM *p)
{
	printf("istore_2");
}
int vf_istore_3(PRM *p)
{
	printf("istore_3");
}
int vf_isub(PRM *p)
{
	printf("isub");
}
int vf_iushr(PRM *p)
{
	printf("iushr");
}
int vf_ixor(PRM *p)
{
	printf("ixor");
}
int vf_jsr(PRM *p)
{
	printf("jsr");
}
int vf_jsr_w(PRM *p)
{
	printf("jsr_w");
}
int vf_l2d(PRM *p)
{
	printf("l2d");
}
int vf_l2f(PRM *p)
{
	printf("l2f");
}
int vf_l2i(PRM *p)
{
	printf("l2i");
}
int vf_ladd(PRM *p)
{
	printf("ladd");
}
int vf_laload(PRM *p)
{
	printf("laload");
}
int vf_land(PRM *p)
{
	printf("land");
}
int vf_lastore(PRM *p)
{
	printf("lastore");
}
int vf_lcmp(PRM *p)
{
	printf("lcmp");
}
int vf_lconst_0(PRM *p)
{
	printf("lconst_0");
}
int vf_lconst_1(PRM *p)
{
	printf("lconst_1");
}
int vf_ldc(PRM *p)
{
	printf("ldc");
}
int vf_ldc_w(PRM *p)
{
	printf("ldc_w");
}
int vf_ldc2_w(PRM *p)
{
	printf("ldc2_w");
}
int vf_ldiv(PRM *p)
{
	printf("ldiv");
}
int vf_lload(PRM *p)
{
	printf("lload");
}
int vf_lload_0(PRM *p)
{
	printf("lload_0");
}
int vf_lload_1(PRM *p)
{
	printf("lload_1");
}
int vf_lload_2(PRM *p)
{
	printf("lload_2");
}
int vf_lload_3(PRM *p)
{
	printf("lload_3");
}
int vf_lmul(PRM *p)
{
	printf("lmul");
}
int vf_lneg(PRM *p)
{
	printf("lneg");
}
int vf_lookupswitch(PRM *p)
{
	printf("lookupswitch");
}
int vf_lor(PRM *p)
{
	printf("lor");
}
int vf_lrem(PRM *p)
{
	printf("lrem");
}
int vf_lreturn(PRM *p)
{
	printf("lreturn");
}
int vf_lshl(PRM *p)
{
	printf("lshl");
}
int vf_lshr(PRM *p)
{
	printf("lshr");
}
int vf_lstore(PRM *p)
{
	printf("lstore");
}
int vf_lstore_0(PRM *p)
{
	printf("lstore_0");
}
int vf_lstore_1(PRM *p)
{
	printf("lstore_1");
}
int vf_lstore_2(PRM *p)
{
	printf("lstore_2");
}
int vf_lstore_3(PRM *p)
{
	printf("lstore_3");
}
int vf_lsub(PRM *p)
{
	printf("lsub");
}
int vf_lushr(PRM *p)
{
	printf("lushr");
}
int vf_lxor(PRM *p)
{
	printf("lxor");
}
int vf_monitorenter(PRM *p)
{
	printf("monitorenter");
}
int vf_monitorexit(PRM *p)
{
	printf("monitorexit");
}
int vf_multianewarray(PRM *p)
{
	printf("multianewarray");
}
int vf_new(PRM *p)
{
	printf("new");
}
int vf_newarray(PRM *p)
{
	printf("newarray");
}
int vf_nop(PRM *p)
{
	printf("nop");
}
int vf_pop(PRM *p)
{
	printf("pop");
}
int vf_pop2(PRM *p)
{
	printf("pop2");
}
int vf_putfield(PRM *p)
{
	printf("putfield");
}
int vf_putstatic(PRM *p)
{
	printf("putstatic");
}
int vf_ret(PRM *p)
{
	printf("ret");
}
int vf_return(PRM *p)
{
	printf("return");
}
int vf_saload(PRM *p)
{
	printf("saload");
}
int vf_sastore(PRM *p)
{
	printf("sastore");
}
int vf_sipush(PRM *p)
{
	printf("sipush");
}
int vf_swap(PRM *p)
{
	printf("swap");
}
int vf_tableswitch(PRM *p)
{
	printf("tableswitch");
}
int vf_wide(PRM *p)
{
	printf("wide");
}
/*
typedef struct _BYTECODE_LUT
{
    unsigned short int n;
    virtual_func vf;
    char *mnem;
} BYTECODE_LUT;
*/
/*
BYTECODE_LUT byte_code_lut[256]= {0};
*/
//extern BYTECODE_LUT[] byte_code_lut;
#ifndef BYTECODE_LUT_INCLUDED
#define BYTECODE_LUT_INCLUDED
//BYTECODE_LUT byte_code_lut[256]= {0};
#endif
// BYTECODE_LUT_INCLUDED
int init_byte_code(void)
{


	byte_code_lut[0x32].n=0;
	byte_code_lut[0x32].vf=&vf_aaload;
	byte_code_lut[0x32].mnem="aaload";

	byte_code_lut[0x53].n=0;
	byte_code_lut[0x53].vf=&vf_aastore;
	byte_code_lut[0x53].mnem="aastore";

	byte_code_lut[0x01].n=0;
	byte_code_lut[0x01].vf=&vf_aconst_null;
	byte_code_lut[0x01].mnem="aconst_null";

	byte_code_lut[0x19].n=0;
	byte_code_lut[0x19].vf=&vf_aload;
	byte_code_lut[0x19].mnem="aload";

	byte_code_lut[0x2a].n=0;
	byte_code_lut[0x2a].vf=&vf_aload_0;
	byte_code_lut[0x2a].mnem="aload_0";

	byte_code_lut[0x2b].n=0;
	byte_code_lut[0x2b].vf=&vf_aload_1;
	byte_code_lut[0x2b].mnem="aload_1";

	byte_code_lut[0x2c].n=0;
	byte_code_lut[0x2c].vf=&vf_aload_2;
	byte_code_lut[0x2c].mnem="aload_2";

	byte_code_lut[0x2d].n=0;
	byte_code_lut[0x2d].vf=&vf_aload_3;
	byte_code_lut[0x2d].mnem="aload_3";

	byte_code_lut[0xbd].n=0;
	byte_code_lut[0xbd].vf=&vf_anewarray;
	byte_code_lut[0xbd].mnem="anewarray";

	byte_code_lut[0xb0].n=0;
	byte_code_lut[0xb0].vf=&vf_areturn;
	byte_code_lut[0xb0].mnem="areturn";

	byte_code_lut[0xbe].n=0;
	byte_code_lut[0xbe].vf=&vf_arraylength;
	byte_code_lut[0xbe].mnem="arraylength";

	byte_code_lut[0x3a].n=0;
	byte_code_lut[0x3a].vf=&vf_astore;
	byte_code_lut[0x3a].mnem="astore";

	byte_code_lut[0x4b].n=0;
	byte_code_lut[0x4b].vf=&vf_astore_0;
	byte_code_lut[0x4b].mnem="astore_0";

	byte_code_lut[0x4c].n=0;
	byte_code_lut[0x4c].vf=&vf_astore_1;
	byte_code_lut[0x4c].mnem="astore_1";

	byte_code_lut[0x4d].n=0;
	byte_code_lut[0x4d].vf=&vf_astore_2;
	byte_code_lut[0x4d].mnem="astore_2";

	byte_code_lut[0x4e].n=0;
	byte_code_lut[0x4e].vf=&vf_astore_3;
	byte_code_lut[0x4e].mnem="astore_3";

	byte_code_lut[0xbf].n=0;
	byte_code_lut[0xbf].vf=&vf_athrow;
	byte_code_lut[0xbf].mnem="athrow";

	byte_code_lut[0x33].n=0;
	byte_code_lut[0x33].vf=&vf_baload;
	byte_code_lut[0x33].mnem="baload";

	byte_code_lut[0x54].n=0;
	byte_code_lut[0x54].vf=&vf_bastore;
	byte_code_lut[0x54].mnem="bastore";

	byte_code_lut[0x10].n=0;
	byte_code_lut[0x10].vf=&vf_bipush;
	byte_code_lut[0x10].mnem="bipush";

	byte_code_lut[0xca].n=0;
	byte_code_lut[0xca].vf=&vf_breakpoint;
	byte_code_lut[0xca].mnem="breakpoint";

	byte_code_lut[0x34].n=0;
	byte_code_lut[0x34].vf=&vf_caload;
	byte_code_lut[0x34].mnem="caload";

	byte_code_lut[0x55].n=0;
	byte_code_lut[0x55].vf=&vf_castore;
	byte_code_lut[0x55].mnem="castore";

	byte_code_lut[0xc0].n=0;
	byte_code_lut[0xc0].vf=&vf_checkcast;
	byte_code_lut[0xc0].mnem="checkcast";

	byte_code_lut[0x90].n=0;
	byte_code_lut[0x90].vf=&vf_d2f;
	byte_code_lut[0x90].mnem="d2f";

	byte_code_lut[0x8e].n=0;
	byte_code_lut[0x8e].vf=&vf_d2i;
	byte_code_lut[0x8e].mnem="d2i";

	byte_code_lut[0x8f].n=0;
	byte_code_lut[0x8f].vf=&vf_d2l;
	byte_code_lut[0x8f].mnem="d2l";

	byte_code_lut[0x63].n=0;
	byte_code_lut[0x63].vf=&vf_dadd;
	byte_code_lut[0x63].mnem="dadd";

	byte_code_lut[0x31].n=0;
	byte_code_lut[0x31].vf=&vf_daload;
	byte_code_lut[0x31].mnem="daload";

	byte_code_lut[0x52].n=0;
	byte_code_lut[0x52].vf=&vf_dastore;
	byte_code_lut[0x52].mnem="dastore";

	byte_code_lut[0x98].n=0;
	byte_code_lut[0x98].vf=&vf_dcmpg;
	byte_code_lut[0x98].mnem="dcmpg";

	byte_code_lut[0x97].n=0;
	byte_code_lut[0x97].vf=&vf_dcmpl;
	byte_code_lut[0x97].mnem="dcmpl";

	byte_code_lut[0x0e].n=0;
	byte_code_lut[0x0e].vf=&vf_dconst_0;
	byte_code_lut[0x0e].mnem="dconst_0";

	byte_code_lut[0x0f].n=0;
	byte_code_lut[0x0f].vf=&vf_dconst_1;
	byte_code_lut[0x0f].mnem="dconst_1";

	byte_code_lut[0x6f].n=0;
	byte_code_lut[0x6f].vf=&vf_ddiv;
	byte_code_lut[0x6f].mnem="ddiv";

	byte_code_lut[0x18].n=0;
	byte_code_lut[0x18].vf=&vf_dload;
	byte_code_lut[0x18].mnem="dload";

	byte_code_lut[0x26].n=0;
	byte_code_lut[0x26].vf=&vf_dload_0;
	byte_code_lut[0x26].mnem="dload_0";

	byte_code_lut[0x27].n=0;
	byte_code_lut[0x27].vf=&vf_dload_1;
	byte_code_lut[0x27].mnem="dload_1";

	byte_code_lut[0x28].n=0;
	byte_code_lut[0x28].vf=&vf_dload_2;
	byte_code_lut[0x28].mnem="dload_2";

	byte_code_lut[0x29].n=0;
	byte_code_lut[0x29].vf=&vf_dload_3;
	byte_code_lut[0x29].mnem="dload_3";

	byte_code_lut[0x6b].n=0;
	byte_code_lut[0x6b].vf=&vf_dmul;
	byte_code_lut[0x6b].mnem="dmul";

	byte_code_lut[0x77].n=0;
	byte_code_lut[0x77].vf=&vf_dneg;
	byte_code_lut[0x77].mnem="dneg";

	byte_code_lut[0x73].n=0;
	byte_code_lut[0x73].vf=&vf_drem;
	byte_code_lut[0x73].mnem="drem";

	byte_code_lut[0xaf].n=0;
	byte_code_lut[0xaf].vf=&vf_dreturn;
	byte_code_lut[0xaf].mnem="dreturn";

	byte_code_lut[0x39].n=0;
	byte_code_lut[0x39].vf=&vf_dstore;
	byte_code_lut[0x39].mnem="dstore";

	byte_code_lut[0x47].n=0;
	byte_code_lut[0x47].vf=&vf_dstore_0;
	byte_code_lut[0x47].mnem="dstore_0";

	byte_code_lut[0x48].n=0;
	byte_code_lut[0x48].vf=&vf_dstore_1;
	byte_code_lut[0x48].mnem="dstore_1";

	byte_code_lut[0x49].n=0;
	byte_code_lut[0x49].vf=&vf_dstore_2;
	byte_code_lut[0x49].mnem="dstore_2";

	byte_code_lut[0x4a].n=0;
	byte_code_lut[0x4a].vf=&vf_dstore_3;
	byte_code_lut[0x4a].mnem="dstore_3";

	byte_code_lut[0x67].n=0;
	byte_code_lut[0x67].vf=&vf_dsub;
	byte_code_lut[0x67].mnem="dsub";

	byte_code_lut[0x59].n=0;
	byte_code_lut[0x59].vf=&vf_dup;
	byte_code_lut[0x59].mnem="dup";

	byte_code_lut[0x5a].n=0;
	byte_code_lut[0x5a].vf=&vf_dup_x1;
	byte_code_lut[0x5a].mnem="dup_x1";

	byte_code_lut[0x5b].n=0;
	byte_code_lut[0x5b].vf=&vf_dup_x2;
	byte_code_lut[0x5b].mnem="dup_x2";

	byte_code_lut[0x5c].n=0;
	byte_code_lut[0x5c].vf=&vf_dup2;
	byte_code_lut[0x5c].mnem="dup2";

	byte_code_lut[0x5d].n=0;
	byte_code_lut[0x5d].vf=&vf_dup2_x1;
	byte_code_lut[0x5d].mnem="dup2_x1";

	byte_code_lut[0x5e].n=0;
	byte_code_lut[0x5e].vf=&vf_dup2_x2;
	byte_code_lut[0x5e].mnem="dup2_x2";

	byte_code_lut[0x8d].n=0;
	byte_code_lut[0x8d].vf=&vf_f2d;
	byte_code_lut[0x8d].mnem="f2d";

	byte_code_lut[0x8b].n=0;
	byte_code_lut[0x8b].vf=&vf_f2i;
	byte_code_lut[0x8b].mnem="f2i";

	byte_code_lut[0x8c].n=0;
	byte_code_lut[0x8c].vf=&vf_f2l;
	byte_code_lut[0x8c].mnem="f2l";

	byte_code_lut[0x62].n=0;
	byte_code_lut[0x62].vf=&vf_fadd;
	byte_code_lut[0x62].mnem="fadd";

	byte_code_lut[0x30].n=0;
	byte_code_lut[0x30].vf=&vf_faload;
	byte_code_lut[0x30].mnem="faload";

	byte_code_lut[0x51].n=0;
	byte_code_lut[0x51].vf=&vf_fastore;
	byte_code_lut[0x51].mnem="fastore";

	byte_code_lut[0x96].n=0;
	byte_code_lut[0x96].vf=&vf_fcmpg;
	byte_code_lut[0x96].mnem="fcmpg";

	byte_code_lut[0x95].n=0;
	byte_code_lut[0x95].vf=&vf_fcmpl;
	byte_code_lut[0x95].mnem="fcmpl";

	byte_code_lut[0x0b].n=0;
	byte_code_lut[0x0b].vf=&vf_fconst_0;
	byte_code_lut[0x0b].mnem="fconst_0";

	byte_code_lut[0x0c].n=0;
	byte_code_lut[0x0c].vf=&vf_fconst_1;
	byte_code_lut[0x0c].mnem="fconst_1";

	byte_code_lut[0x0d].n=0;
	byte_code_lut[0x0d].vf=&vf_fconst_2;
	byte_code_lut[0x0d].mnem="fconst_2";

	byte_code_lut[0x6e].n=0;
	byte_code_lut[0x6e].vf=&vf_fdiv;
	byte_code_lut[0x6e].mnem="fdiv";

	byte_code_lut[0x17].n=0;
	byte_code_lut[0x17].vf=&vf_fload;
	byte_code_lut[0x17].mnem="fload";

	byte_code_lut[0x22].n=0;
	byte_code_lut[0x22].vf=&vf_fload_0;
	byte_code_lut[0x22].mnem="fload_0";

	byte_code_lut[0x23].n=0;
	byte_code_lut[0x23].vf=&vf_fload_1;
	byte_code_lut[0x23].mnem="fload_1";

	byte_code_lut[0x24].n=0;
	byte_code_lut[0x24].vf=&vf_fload_2;
	byte_code_lut[0x24].mnem="fload_2";

	byte_code_lut[0x25].n=0;
	byte_code_lut[0x25].vf=&vf_fload_3;
	byte_code_lut[0x25].mnem="fload_3";

	byte_code_lut[0x6a].n=0;
	byte_code_lut[0x6a].vf=&vf_fmul;
	byte_code_lut[0x6a].mnem="fmul";

	byte_code_lut[0x76].n=0;
	byte_code_lut[0x76].vf=&vf_fneg;
	byte_code_lut[0x76].mnem="fneg";

	byte_code_lut[0x72].n=0;
	byte_code_lut[0x72].vf=&vf_frem;
	byte_code_lut[0x72].mnem="frem";

	byte_code_lut[0xae].n=0;
	byte_code_lut[0xae].vf=&vf_freturn;
	byte_code_lut[0xae].mnem="freturn";

	byte_code_lut[0x38].n=0;
	byte_code_lut[0x38].vf=&vf_fstore;
	byte_code_lut[0x38].mnem="fstore";

	byte_code_lut[0x43].n=0;
	byte_code_lut[0x43].vf=&vf_fstore_0;
	byte_code_lut[0x43].mnem="fstore_0";

	byte_code_lut[0x44].n=0;
	byte_code_lut[0x44].vf=&vf_fstore_1;
	byte_code_lut[0x44].mnem="fstore_1";

	byte_code_lut[0x45].n=0;
	byte_code_lut[0x45].vf=&vf_fstore_2;
	byte_code_lut[0x45].mnem="fstore_2";

	byte_code_lut[0x46].n=0;
	byte_code_lut[0x46].vf=&vf_fstore_3;
	byte_code_lut[0x46].mnem="fstore_3";

	byte_code_lut[0x66].n=0;
	byte_code_lut[0x66].vf=&vf_fsub;
	byte_code_lut[0x66].mnem="fsub";

	byte_code_lut[0xb4].n=0;
	byte_code_lut[0xb4].vf=&vf_getfield;
	byte_code_lut[0xb4].mnem="getfield";

	byte_code_lut[0xb2].n=0;
	byte_code_lut[0xb2].vf=&vf_getstatic;
	byte_code_lut[0xb2].mnem="getstatic";

	byte_code_lut[0xa7].n=0;
	byte_code_lut[0xa7].vf=&vf_goto;
	byte_code_lut[0xa7].mnem="goto";

	byte_code_lut[0xc8].n=0;
	byte_code_lut[0xc8].vf=&vf_goto_w;
	byte_code_lut[0xc8].mnem="goto_w";

	byte_code_lut[0x91].n=0;
	byte_code_lut[0x91].vf=&vf_i2b;
	byte_code_lut[0x91].mnem="i2b";

	byte_code_lut[0x92].n=0;
	byte_code_lut[0x92].vf=&vf_i2c;
	byte_code_lut[0x92].mnem="i2c";

	byte_code_lut[0x87].n=0;
	byte_code_lut[0x87].vf=&vf_i2d;
	byte_code_lut[0x87].mnem="i2d";

	byte_code_lut[0x86].n=0;
	byte_code_lut[0x86].vf=&vf_i2f;
	byte_code_lut[0x86].mnem="i2f";

	byte_code_lut[0x85].n=0;
	byte_code_lut[0x85].vf=&vf_i2l;
	byte_code_lut[0x85].mnem="i2l";

	byte_code_lut[0x93].n=0;
	byte_code_lut[0x93].vf=&vf_i2s;
	byte_code_lut[0x93].mnem="i2s";

	byte_code_lut[0x60].n=0;
	byte_code_lut[0x60].vf=&vf_iadd;
	byte_code_lut[0x60].mnem="iadd";

	byte_code_lut[0x2e].n=0;
	byte_code_lut[0x2e].vf=&vf_iaload;
	byte_code_lut[0x2e].mnem="iaload";

	byte_code_lut[0x7e].n=0;
	byte_code_lut[0x7e].vf=&vf_iand;
	byte_code_lut[0x7e].mnem="iand";

	byte_code_lut[0x4f].n=0;
	byte_code_lut[0x4f].vf=&vf_iastore;
	byte_code_lut[0x4f].mnem="iastore";

	byte_code_lut[0x02].n=0;
	byte_code_lut[0x02].vf=&vf_iconst_m1;
	byte_code_lut[0x02].mnem="iconst_m1";

	byte_code_lut[0x03].n=0;
	byte_code_lut[0x03].vf=&vf_iconst_0;
	byte_code_lut[0x03].mnem="iconst_0";

	byte_code_lut[0x04].n=0;
	byte_code_lut[0x04].vf=&vf_iconst_1;
	byte_code_lut[0x04].mnem="iconst_1";

	byte_code_lut[0x05].n=0;
	byte_code_lut[0x05].vf=&vf_iconst_2;
	byte_code_lut[0x05].mnem="iconst_2";

	byte_code_lut[0x06].n=0;
	byte_code_lut[0x06].vf=&vf_iconst_3;
	byte_code_lut[0x06].mnem="iconst_3";

	byte_code_lut[0x07].n=0;
	byte_code_lut[0x07].vf=&vf_iconst_4;
	byte_code_lut[0x07].mnem="iconst_4";

	byte_code_lut[0x08].n=0;
	byte_code_lut[0x08].vf=&vf_iconst_5;
	byte_code_lut[0x08].mnem="iconst_5";

	byte_code_lut[0x6c].n=0;
	byte_code_lut[0x6c].vf=&vf_idiv;
	byte_code_lut[0x6c].mnem="idiv";

	byte_code_lut[0xa5].n=0;
	byte_code_lut[0xa5].vf=&vf_if_acmpeq;
	byte_code_lut[0xa5].mnem="if_acmpeq";

	byte_code_lut[0xa6].n=0;
	byte_code_lut[0xa6].vf=&vf_if_acmpne;
	byte_code_lut[0xa6].mnem="if_acmpne";

	byte_code_lut[0x9f].n=0;
	byte_code_lut[0x9f].vf=&vf_if_icmpeq;
	byte_code_lut[0x9f].mnem="if_icmpeq";

	byte_code_lut[0xa2].n=0;
	byte_code_lut[0xa2].vf=&vf_if_icmpge;
	byte_code_lut[0xa2].mnem="if_icmpge";

	byte_code_lut[0xa3].n=0;
	byte_code_lut[0xa3].vf=&vf_if_icmpgt;
	byte_code_lut[0xa3].mnem="if_icmpgt";

	byte_code_lut[0xa4].n=0;
	byte_code_lut[0xa4].vf=&vf_if_icmple;
	byte_code_lut[0xa4].mnem="if_icmple";

	byte_code_lut[0xa1].n=0;
	byte_code_lut[0xa1].vf=&vf_if_icmplt;
	byte_code_lut[0xa1].mnem="if_icmplt";

	byte_code_lut[0xa0].n=0;
	byte_code_lut[0xa0].vf=&vf_if_icmpne;
	byte_code_lut[0xa0].mnem="if_icmpne";

	byte_code_lut[0x99].n=0;
	byte_code_lut[0x99].vf=&vf_ifeq;
	byte_code_lut[0x99].mnem="ifeq";

	byte_code_lut[0x9c].n=0;
	byte_code_lut[0x9c].vf=&vf_ifge;
	byte_code_lut[0x9c].mnem="ifge";

	byte_code_lut[0x9d].n=0;
	byte_code_lut[0x9d].vf=&vf_ifgt;
	byte_code_lut[0x9d].mnem="ifgt";

	byte_code_lut[0x9e].n=0;
	byte_code_lut[0x9e].vf=&vf_ifle;
	byte_code_lut[0x9e].mnem="ifle";

	byte_code_lut[0x9b].n=0;
	byte_code_lut[0x9b].vf=&vf_iflt;
	byte_code_lut[0x9b].mnem="iflt";

	byte_code_lut[0x9a].n=0;
	byte_code_lut[0x9a].vf=&vf_ifne;
	byte_code_lut[0x9a].mnem="ifne";

	byte_code_lut[0xc7].n=0;
	byte_code_lut[0xc7].vf=&vf_ifnonnull;
	byte_code_lut[0xc7].mnem="ifnonnull";

	byte_code_lut[0xc6].n=0;
	byte_code_lut[0xc6].vf=&vf_ifnull;
	byte_code_lut[0xc6].mnem="ifnull";

	byte_code_lut[0x84].n=0;
	byte_code_lut[0x84].vf=&vf_iinc;
	byte_code_lut[0x84].mnem="iinc";

	byte_code_lut[0x15].n=0;
	byte_code_lut[0x15].vf=&vf_iload;
	byte_code_lut[0x15].mnem="iload";

	byte_code_lut[0x1a].n=0;
	byte_code_lut[0x1a].vf=&vf_iload_0;
	byte_code_lut[0x1a].mnem="iload_0";

	byte_code_lut[0x1b].n=0;
	byte_code_lut[0x1b].vf=&vf_iload_1;
	byte_code_lut[0x1b].mnem="iload_1";

	byte_code_lut[0x1c].n=0;
	byte_code_lut[0x1c].vf=&vf_iload_2;
	byte_code_lut[0x1c].mnem="iload_2";

	byte_code_lut[0x1d].n=0;
	byte_code_lut[0x1d].vf=&vf_iload_3;
	byte_code_lut[0x1d].mnem="iload_3";

	byte_code_lut[0xfe].n=0;
	byte_code_lut[0xfe].vf=&vf_impdep1;
	byte_code_lut[0xfe].mnem="impdep1";

	byte_code_lut[0xff].n=0;
	byte_code_lut[0xff].vf=&vf_impdep2;
	byte_code_lut[0xff].mnem="impdep2";

	byte_code_lut[0x68].n=0;
	byte_code_lut[0x68].vf=&vf_imul;
	byte_code_lut[0x68].mnem="imul";

	byte_code_lut[0x74].n=0;
	byte_code_lut[0x74].vf=&vf_ineg;
	byte_code_lut[0x74].mnem="ineg";

	byte_code_lut[0xc1].n=0;
	byte_code_lut[0xc1].vf=&vf_instanceof;
	byte_code_lut[0xc1].mnem="instanceof";

	byte_code_lut[0xba].n=0;
	byte_code_lut[0xba].vf=&vf_invokedynamic;
	byte_code_lut[0xba].mnem="invokedynamic";

	byte_code_lut[0xb9].n=0;
	byte_code_lut[0xb9].vf=&vf_invokeinterface;
	byte_code_lut[0xb9].mnem="invokeinterface";

	byte_code_lut[0xb7].n=0;
	byte_code_lut[0xb7].vf=&vf_invokespecial;
	byte_code_lut[0xb7].mnem="invokespecial";

	byte_code_lut[0xb8].n=0;
	byte_code_lut[0xb8].vf=&vf_invokestatic;
	byte_code_lut[0xb8].mnem="invokestatic";

	byte_code_lut[0xb6].n=0;
	byte_code_lut[0xb6].vf=&vf_invokevirtual;
	byte_code_lut[0xb6].mnem="invokevirtual";

	byte_code_lut[0x80].n=0;
	byte_code_lut[0x80].vf=&vf_ior;
	byte_code_lut[0x80].mnem="ior";

	byte_code_lut[0x70].n=0;
	byte_code_lut[0x70].vf=&vf_irem;
	byte_code_lut[0x70].mnem="irem";

	byte_code_lut[0xac].n=0;
	byte_code_lut[0xac].vf=&vf_ireturn;
	byte_code_lut[0xac].mnem="ireturn";

	byte_code_lut[0x78].n=0;
	byte_code_lut[0x78].vf=&vf_ishl;
	byte_code_lut[0x78].mnem="ishl";

	byte_code_lut[0x7a].n=0;
	byte_code_lut[0x7a].vf=&vf_ishr;
	byte_code_lut[0x7a].mnem="ishr";

	byte_code_lut[0x36].n=0;
	byte_code_lut[0x36].vf=&vf_istore;
	byte_code_lut[0x36].mnem="istore";

	byte_code_lut[0x3b].n=0;
	byte_code_lut[0x3b].vf=&vf_istore_0;
	byte_code_lut[0x3b].mnem="istore_0";

	byte_code_lut[0x3c].n=0;
	byte_code_lut[0x3c].vf=&vf_istore_1;
	byte_code_lut[0x3c].mnem="istore_1";

	byte_code_lut[0x3d].n=0;
	byte_code_lut[0x3d].vf=&vf_istore_2;
	byte_code_lut[0x3d].mnem="istore_2";

	byte_code_lut[0x3e].n=0;
	byte_code_lut[0x3e].vf=&vf_istore_3;
	byte_code_lut[0x3e].mnem="istore_3";

	byte_code_lut[0x64].n=0;
	byte_code_lut[0x64].vf=&vf_isub;
	byte_code_lut[0x64].mnem="isub";

	byte_code_lut[0x7c].n=0;
	byte_code_lut[0x7c].vf=&vf_iushr;
	byte_code_lut[0x7c].mnem="iushr";

	byte_code_lut[0x82].n=0;
	byte_code_lut[0x82].vf=&vf_ixor;
	byte_code_lut[0x82].mnem="ixor";

	byte_code_lut[0xa8].n=0;
	byte_code_lut[0xa8].vf=&vf_jsr;
	byte_code_lut[0xa8].mnem="jsr";

	byte_code_lut[0xc9].n=0;
	byte_code_lut[0xc9].vf=&vf_jsr_w;
	byte_code_lut[0xc9].mnem="jsr_w";

	byte_code_lut[0x8a].n=0;
	byte_code_lut[0x8a].vf=&vf_l2d;
	byte_code_lut[0x8a].mnem="l2d";

	byte_code_lut[0x89].n=0;
	byte_code_lut[0x89].vf=&vf_l2f;
	byte_code_lut[0x89].mnem="l2f";

	byte_code_lut[0x88].n=0;
	byte_code_lut[0x88].vf=&vf_l2i;
	byte_code_lut[0x88].mnem="l2i";

	byte_code_lut[0x61].n=0;
	byte_code_lut[0x61].vf=&vf_ladd;
	byte_code_lut[0x61].mnem="ladd";

	byte_code_lut[0x2f].n=0;
	byte_code_lut[0x2f].vf=&vf_laload;
	byte_code_lut[0x2f].mnem="laload";

	byte_code_lut[0x7f].n=0;
	byte_code_lut[0x7f].vf=&vf_land;
	byte_code_lut[0x7f].mnem="land";

	byte_code_lut[0x50].n=0;
	byte_code_lut[0x50].vf=&vf_lastore;
	byte_code_lut[0x50].mnem="lastore";

	byte_code_lut[0x94].n=0;
	byte_code_lut[0x94].vf=&vf_lcmp;
	byte_code_lut[0x94].mnem="lcmp";

	byte_code_lut[0x09].n=0;
	byte_code_lut[0x09].vf=&vf_lconst_0;
	byte_code_lut[0x09].mnem="lconst_0";

	byte_code_lut[0x0a].n=0;
	byte_code_lut[0x0a].vf=&vf_lconst_1;
	byte_code_lut[0x0a].mnem="lconst_1";

	byte_code_lut[0x12].n=0;
	byte_code_lut[0x12].vf=&vf_ldc;
	byte_code_lut[0x12].mnem="ldc";

	byte_code_lut[0x13].n=0;
	byte_code_lut[0x13].vf=&vf_ldc_w;
	byte_code_lut[0x13].mnem="ldc_w";

	byte_code_lut[0x14].n=0;
	byte_code_lut[0x14].vf=&vf_ldc2_w;
	byte_code_lut[0x14].mnem="ldc2_w";

	byte_code_lut[0x6d].n=0;
	byte_code_lut[0x6d].vf=&vf_ldiv;
	byte_code_lut[0x6d].mnem="ldiv";

	byte_code_lut[0x16].n=0;
	byte_code_lut[0x16].vf=&vf_lload;
	byte_code_lut[0x16].mnem="lload";

	byte_code_lut[0x1e].n=0;
	byte_code_lut[0x1e].vf=&vf_lload_0;
	byte_code_lut[0x1e].mnem="lload_0";

	byte_code_lut[0x1f].n=0;
	byte_code_lut[0x1f].vf=&vf_lload_1;
	byte_code_lut[0x1f].mnem="lload_1";

	byte_code_lut[0x20].n=0;
	byte_code_lut[0x20].vf=&vf_lload_2;
	byte_code_lut[0x20].mnem="lload_2";

	byte_code_lut[0x21].n=0;
	byte_code_lut[0x21].vf=&vf_lload_3;
	byte_code_lut[0x21].mnem="lload_3";

	byte_code_lut[0x69].n=0;
	byte_code_lut[0x69].vf=&vf_lmul;
	byte_code_lut[0x69].mnem="lmul";

	byte_code_lut[0x75].n=0;
	byte_code_lut[0x75].vf=&vf_lneg;
	byte_code_lut[0x75].mnem="lneg";

	byte_code_lut[0xab].n=0;
	byte_code_lut[0xab].vf=&vf_lookupswitch;
	byte_code_lut[0xab].mnem="lookupswitch";

	byte_code_lut[0x81].n=0;
	byte_code_lut[0x81].vf=&vf_lor;
	byte_code_lut[0x81].mnem="lor";

	byte_code_lut[0x71].n=0;
	byte_code_lut[0x71].vf=&vf_lrem;
	byte_code_lut[0x71].mnem="lrem";

	byte_code_lut[0xad].n=0;
	byte_code_lut[0xad].vf=&vf_lreturn;
	byte_code_lut[0xad].mnem="lreturn";

	byte_code_lut[0x79].n=0;
	byte_code_lut[0x79].vf=&vf_lshl;
	byte_code_lut[0x79].mnem="lshl";

	byte_code_lut[0x7b].n=0;
	byte_code_lut[0x7b].vf=&vf_lshr;
	byte_code_lut[0x7b].mnem="lshr";

	byte_code_lut[0x37].n=0;
	byte_code_lut[0x37].vf=&vf_lstore;
	byte_code_lut[0x37].mnem="lstore";

	byte_code_lut[0x3f].n=0;
	byte_code_lut[0x3f].vf=&vf_lstore_0;
	byte_code_lut[0x3f].mnem="lstore_0";

	byte_code_lut[0x40].n=0;
	byte_code_lut[0x40].vf=&vf_lstore_1;
	byte_code_lut[0x40].mnem="lstore_1";

	byte_code_lut[0x41].n=0;
	byte_code_lut[0x41].vf=&vf_lstore_2;
	byte_code_lut[0x41].mnem="lstore_2";

	byte_code_lut[0x42].n=0;
	byte_code_lut[0x42].vf=&vf_lstore_3;
	byte_code_lut[0x42].mnem="lstore_3";

	byte_code_lut[0x65].n=0;
	byte_code_lut[0x65].vf=&vf_lsub;
	byte_code_lut[0x65].mnem="lsub";

	byte_code_lut[0x7d].n=0;
	byte_code_lut[0x7d].vf=&vf_lushr;
	byte_code_lut[0x7d].mnem="lushr";

	byte_code_lut[0x83].n=0;
	byte_code_lut[0x83].vf=&vf_lxor;
	byte_code_lut[0x83].mnem="lxor";

	byte_code_lut[0xc2].n=0;
	byte_code_lut[0xc2].vf=&vf_monitorenter;
	byte_code_lut[0xc2].mnem="monitorenter";

	byte_code_lut[0xc3].n=0;
	byte_code_lut[0xc3].vf=&vf_monitorexit;
	byte_code_lut[0xc3].mnem="monitorexit";

	byte_code_lut[0xc5].n=0;
	byte_code_lut[0xc5].vf=&vf_multianewarray;
	byte_code_lut[0xc5].mnem="multianewarray";

	byte_code_lut[0xbb].n=0;
	byte_code_lut[0xbb].vf=&vf_new;
	byte_code_lut[0xbb].mnem="new";

	byte_code_lut[0xbc].n=0;
	byte_code_lut[0xbc].vf=&vf_newarray;
	byte_code_lut[0xbc].mnem="newarray";

	byte_code_lut[0x00].n=0;
	byte_code_lut[0x00].vf=&vf_nop;
	byte_code_lut[0x00].mnem="nop";

	byte_code_lut[0x57].n=0;
	byte_code_lut[0x57].vf=&vf_pop;
	byte_code_lut[0x57].mnem="pop";

	byte_code_lut[0x58].n=0;
	byte_code_lut[0x58].vf=&vf_pop2;
	byte_code_lut[0x58].mnem="pop2";

	byte_code_lut[0xb5].n=0;
	byte_code_lut[0xb5].vf=&vf_putfield;
	byte_code_lut[0xb5].mnem="putfield";

	byte_code_lut[0xb3].n=0;
	byte_code_lut[0xb3].vf=&vf_putstatic;
	byte_code_lut[0xb3].mnem="putstatic";

	byte_code_lut[0xa9].n=0;
	byte_code_lut[0xa9].vf=&vf_ret;
	byte_code_lut[0xa9].mnem="ret";

	byte_code_lut[0xb1].n=0;
	byte_code_lut[0xb1].vf=&vf_return;
	byte_code_lut[0xb1].mnem="return";

	byte_code_lut[0x35].n=0;
	byte_code_lut[0x35].vf=&vf_saload;
	byte_code_lut[0x35].mnem="saload";

	byte_code_lut[0x56].n=0;
	byte_code_lut[0x56].vf=&vf_sastore;
	byte_code_lut[0x56].mnem="sastore";

	byte_code_lut[0x11].n=0;
	byte_code_lut[0x11].vf=&vf_sipush;
	byte_code_lut[0x11].mnem="sipush";

	byte_code_lut[0x5f].n=0;
	byte_code_lut[0x5f].vf=&vf_swap;
	byte_code_lut[0x5f].mnem="swap";

	byte_code_lut[0xaa].n=0;
	byte_code_lut[0xaa].vf=&vf_tableswitch;
	byte_code_lut[0xaa].mnem="tableswitch";

	byte_code_lut[0xc4].n=0;
	byte_code_lut[0xc4].vf=&vf_wide;
	byte_code_lut[0xc4].mnem="wide";


}
